package Vistas;

import Conexión.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pixie
 */
public class LoginEjec extends javax.swing.JFrame {

    /**
     * Creates new form LoginEjec
     */
    public LoginEjec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_adminc = new javax.swing.JButton();
        btn_gestions = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnConsultarEC = new javax.swing.JButton();
        btnValidarPagos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_adminc.setText("Administrar Contrato");
        btn_adminc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admincActionPerformed(evt);
            }
        });
        getContentPane().add(btn_adminc);
        btn_adminc.setBounds(100, 70, 190, 30);

        btn_gestions.setText("Gestionar Seguro");
        getContentPane().add(btn_gestions);
        btn_gestions.setBounds(100, 120, 190, 30);

        btn_Cancelar.setText("Salir");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancelar);
        btn_Cancelar.setBounds(250, 270, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú ejecutiva/o de ventas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 340, 40);

        btnConsultarEC.setText("Consultar Estado de Cuenta");
        btnConsultarEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarECActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarEC);
        btnConsultarEC.setBounds(100, 170, 190, 30);

        btnValidarPagos.setText("Validar Pagos");
        btnValidarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarPagosActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidarPagos);
        btnValidarPagos.setBounds(100, 220, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mmmm.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btnConsultarECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarECActionPerformed
        this.setVisible(false);
        new ConsultarEstadoCuenta().setVisible(true);
    }//GEN-LAST:event_btnConsultarECActionPerformed

    private void btnValidarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarPagosActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new ValidarPagos().setVisible(true);
    }//GEN-LAST:event_btnValidarPagosActionPerformed

    private void btn_admincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admincActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new Contrato().setVisible(true);
    }//GEN-LAST:event_btn_admincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEjec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarEC;
    private javax.swing.JButton btnValidarPagos;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_adminc;
    private javax.swing.JButton btn_gestions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
