
import java.util.HashSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pixie
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    
    MantenedorALumno alum = null;
    MantenedorCurso curso=null;
    MantenedorDestinos destino=null;
    MantenedorCuenta cuenta = null;
    MantenedorActividad actividad = null;
    MantenedorRegiones region = null;
    MantenedorEscuela escuela = null;
    MantenedorCtaRol rol =null;
    MantenedorServicios servicio = null;
    public LoginAdmin() {
        initComponents();
        alum = new MantenedorALumno();
        curso = new MantenedorCurso();
        destino = new MantenedorDestinos();
        cuenta = new MantenedorCuenta();
        actividad = new MantenedorActividad();
        region = new MantenedorRegiones();
        escuela = new MantenedorEscuela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Alumno = new javax.swing.JButton();
        btn_Curso = new javax.swing.JButton();
        btn_Destinos = new javax.swing.JButton();
        btn_Cta = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Region = new javax.swing.JButton();
        btn_Escuela = new javax.swing.JButton();
        btn_CtaRol = new javax.swing.JButton();
        btn_servicios = new javax.swing.JButton();
        btn_Actividad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú Administrador");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 250, 30);

        btn_Alumno.setText("Mantendor Alumno");
        btn_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Alumno);
        btn_Alumno.setBounds(30, 60, 140, 30);

        btn_Curso.setText("Mantenedor Curso");
        btn_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CursoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Curso);
        btn_Curso.setBounds(30, 110, 140, 30);

        btn_Destinos.setText("Mantendor Destinos");
        btn_Destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DestinosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Destinos);
        btn_Destinos.setBounds(30, 160, 140, 30);

        btn_Cta.setText("Mantenedor Cuenta");
        btn_Cta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CtaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cta);
        btn_Cta.setBounds(30, 210, 140, 30);

        btn_Cancelar.setText("Salir");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cancelar);
        btn_Cancelar.setBounds(270, 283, 80, 30);

        btn_Region.setText("Mantenedor región");
        btn_Region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Region);
        btn_Region.setBounds(220, 60, 150, 30);

        btn_Escuela.setText("Mantenedor Escuela");
        btn_Escuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscuelaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Escuela);
        btn_Escuela.setBounds(220, 110, 150, 30);

        btn_CtaRol.setText("Mantenedor Cuenta Rol");
        btn_CtaRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CtaRolActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CtaRol);
        btn_CtaRol.setBounds(220, 160, 150, 30);

        btn_servicios.setText("Mantendor Servicios");
        btn_servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serviciosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_servicios);
        btn_servicios.setBounds(220, 210, 150, 30);

        btn_Actividad.setText("Mantenedor Actividad");
        btn_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActividadActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Actividad);
        btn_Actividad.setBounds(30, 260, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mmmm.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlumnoActionPerformed
        // TODO add your handling code here:
        MantenedorALumno second = new MantenedorALumno();
        
        this.setVisible(false);
        alum.setVisible(true);
        
        //this.dispose();
        
    }//GEN-LAST:event_btn_AlumnoActionPerformed

    private void btn_EscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscuelaActionPerformed
        // TODO add your handling code here:
        MantenedorEscuela second = new MantenedorEscuela();
      
        this.setVisible(false);
        escuela.setVisible(true);

        
        //this.dispose();
        
    }//GEN-LAST:event_btn_EscuelaActionPerformed

    private void btn_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CursoActionPerformed
        // TODO add your handling code here:
        MantenedorCurso second = new MantenedorCurso();
        
        this.setVisible(false);
        curso.setVisible(true);
        
    }//GEN-LAST:event_btn_CursoActionPerformed

    private void btn_serviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serviciosActionPerformed
        // TODO add your handling code here:
       
       
        this.setVisible(false);
        new MantenedorServicios().setVisible(true);
        
    }//GEN-LAST:event_btn_serviciosActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_DestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DestinosActionPerformed
        // TODO add your handling code here:
        MantenedorDestinos second = new MantenedorDestinos();
       
        this.setVisible(false);
        destino.setVisible(true);
        
        
    }//GEN-LAST:event_btn_DestinosActionPerformed

    private void btn_CtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CtaActionPerformed
        // TODO add your handling code here:
        MantenedorCuenta second = new MantenedorCuenta();
        
        this.setVisible(false);
        cuenta.setVisible(true);
        
        
    }//GEN-LAST:event_btn_CtaActionPerformed

    private void btn_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActividadActionPerformed
        // TODO add your handling code here:
        MantenedorActividad second = new MantenedorActividad();
       
        this.setVisible(false); 
        actividad.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_ActividadActionPerformed

    private void btn_RegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegionActionPerformed
        // TODO add your handling code here:
        MantenedorRegiones second = new MantenedorRegiones();
     
        this.setVisible(false);
        new MantenedorRegiones().setVisible(true);
        
        
    }//GEN-LAST:event_btn_RegionActionPerformed

    private void btn_CtaRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CtaRolActionPerformed
        // TODO add your handling code here:
       
        this.setVisible(false);
        new MantenedorCtaRol().setVisible(true);
        
    }//GEN-LAST:event_btn_CtaRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actividad;
    private javax.swing.JButton btn_Alumno;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cta;
    private javax.swing.JButton btn_CtaRol;
    private javax.swing.JButton btn_Curso;
    private javax.swing.JButton btn_Destinos;
    private javax.swing.JButton btn_Escuela;
    private javax.swing.JButton btn_Region;
    private javax.swing.JButton btn_servicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
