
import Clases.ConnectAPI;
import Clases.Curso;
import Clases.Deposito;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramirez
 */
public class ValidarPagos extends javax.swing.JFrame {

    /**
     * Creates new form ValidarPagos
     */
    public ValidarPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeposito = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cboCurso = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CURSO ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 20, 53, 14);

        tablaDeposito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDeposito);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(15, 57, 375, 195);

        jButton1.setText("Buscar PAGOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(262, 16, 101, 23);

        jButton2.setText("APROBAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(72, 270, 81, 23);

        jButton3.setText("RECHAZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(171, 270, 87, 23);

        cboCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCursoMouseClicked(evt);
            }
        });
        getContentPane().add(cboCurso);
        cboCurso.setBounds(119, 17, 116, 20);

        jButton4.setText("Volver");
        getContentPane().add(jButton4);
        jButton4.setBounds(276, 270, 63, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mmmm.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCursoMouseClicked
        // TODO add your handling code here:
        
        try{
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@165.227.213.232:1521:dbportafolio","C##_equipo2","portafolio02");
            Statement sent = conn.createStatement();
            ResultSet rs = sent.executeQuery("Select curso_id from curso");
            while(rs.next())
            {
                
                this.cboCurso.addItem(rs.getString("curso_id"));
            }
            conn.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_cboCursoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
          DefaultTableModel modelo = new DefaultTableModel();

        Deposito[] dep = null;
        ConnectAPI cap = new ConnectAPI();
        String id = cboCurso.getSelectedItem().toString().trim().toLowerCase();
        try{
            modelo.setColumnIdentifiers(new Object[]{"Deposito_ID","cuenta_id","tipo_id","monoto","estado","fecha"});
            dep = cap.listarDepositos(id);
            for (int i = 0; i < dep.length; i++) {
                modelo.addRow(new Object[]{dep[i].getDeposito_id(),dep[i].getCuenta_id(),dep[i].getTipo_id(),dep[i].getMonto(),dep[i].getEstado(),dep[i].getFecha()});
            }
            
            tablaDeposito.setModel(modelo);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       int i = tablaDeposito.getSelectedRow();
        ConnectAPI c = new ConnectAPI();
        boolean exito = false;
        String cuenta_id = tablaDeposito.getValueAt(i,1).toString();
        try{
           exito = c.aprobarDeposito(cuenta_id);
            if(exito==true)
              {
                  System.out.println("APROBADO con exito");  
                  
              }else
              {
                System.out.println("error else");
              }
        }catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("error try");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = tablaDeposito.getSelectedRow();
        ConnectAPI c = new ConnectAPI();
        boolean exito = false;
        String cuenta_id = tablaDeposito.getValueAt(i,1).toString();
        try{
           exito = c.rechazarDeposito(cuenta_id);
            if(exito==true)
              {
                  System.out.println("DEPOSITO RECHAZADO");  
                  
              }else
              {
                System.out.println("error else");
              }
        }catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("error try");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidarPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDeposito;
    // End of variables declaration//GEN-END:variables
}
